In [75]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [76]:
path = ('test_files/Alabama.CSV')

alabama = pd.read_csv(path)
alabama_df = pd.DataFrame(alabama)

In [77]:
#Narrowing down which data we want to look at
alabama_df = alabama_df[((alabama_df.measure_name == 'Life expectancy') &   #Removes mortality rate
                        (alabama_df.sex == 'Both') &                        #Removes Male/Female; simplifies data
                        (alabama_df.location_name != 'Alabama') &           #Removes data for state as a whole
                        (alabama_df.year_id >= 2010))]                      #Limit years to 2010-2014 (arbitrary)  

alabama_df

,measure_id,measure_name,location_id,location_name,FIPS,sex_id,sex,age_id,age_name,year_id,metric,val,upper,lower
205,26,Life expectancy,614,Autauga County,1001,3,Both,161,0,2010,Years,75.740202,76.253238,75.253607
206,26,Life expectancy,614,Autauga County,1001,3,Both,161,0,2011,Years,75.668564,76.189011,75.177995
207,26,Life expectancy,614,Autauga County,1001,3,Both,161,0,2012,Years,75.566091,76.098629,75.020275
208,26,Life expectancy,614,Autauga County,1001,3,Both,161,0,2013,Years,75.503411,76.006642,74.981358
209,26,Life expectancy,614,Autauga County,1001,3,Both,161,0,2014,Years,75.668023,76.183127,75.149553
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7135,26,Life expectancy,587,Winston County,1133,3,Both,161,0,2010,Years,74.423201,75.041113,73.858894
7136,26,Life expectancy,587,Winston County,1133,3,Both,161,0,2011,Years,74.568287,75.164120,73.966230
7137,26,Life expectancy,587,Winston County,1133,3,Both,161,0,2012,Years,74.525053,75.136090,73.906543
7138,26,Life expectancy,587,Winston County,1133,3,Both,161,0,2013,Years,74.518874,75.093618,73.945081
7139,26,Life expectancy,587,Winston County,1133,3,Both,161,0,2014,Years,74.513229,75.137620,73.861035

In [80]:
#remove unneeded columns
alabama_df = alabama_df.drop(['measure_id', 'location_id', 'FIPS', 'sex_id', 'age_id', 'metric', 'upper', 'lower'],axis=1)

In [81]:
alabama_df

         measure_name   location_name   sex age_name  year_id        val
205   Life expectancy  Autauga County  Both        0     2010  75.740202
206   Life expectancy  Autauga County  Both        0     2011  75.668564
207   Life expectancy  Autauga County  Both        0     2012  75.566091
208   Life expectancy  Autauga County  Both        0     2013  75.503411
209   Life expectancy  Autauga County  Both        0     2014  75.668023
...               ...             ...   ...      ...      ...        ...
7135  Life expectancy  Winston County  Both        0     2010  74.423201
7136  Life expectancy  Winston County  Both        0     2011  74.568287
7137  Life expectancy  Winston County  Both        0     2012  74.525053
7138  Life expectancy  Winston County  Both        0     2013  74.518874
7139  Life expectancy  Winston County  Both        0     2014  74.513229

[335 rows x 6 columns]

In [ ]:
#additional features: 
# 1. make heatmap with gmaps or choropleth with another package, such as geopandas
# 2. turn this into a function and apply to each state
# 3. combine total?